version: '2.1'
services:
  ros:
    image: "leontius/ros:hokuyo_ros"
    container_name: hokuyo_ros
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - ./data:/data
      - ./tmp:/tmp
      - ./hokuyo.launch:/home/spin-hokuyo_ws/src/spin_hokuyo-master/launch/tilt_continuous.launch
      - ./dynamixel_servos_tilting.yaml:/home/spin-hokuyo_ws/src/spin_hokuyo-master/launch/dynamixel_servos_tilting.yaml
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
