version: '2.1'
services:
  ros:
    image: "leontius/ros:hokuyo:latest"
    container_name: hokuyo_ros
    hostname: ros
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - ./data:/data
      - ./tmp:/tmp
      - ./hokuyo.launch:/home/spin-hokuyo_ws/src/spin_hokuyo-master/launch/tilt_continuous.launch
      - ./dynamixel_servos_tilting.yaml:/home/spin-hokuyo_ws/src/spin_hokuyo-master/launch/dynamixel_servos_tilting.yaml
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - eye
  hostap:
    image: "leontius/pi-hostap:latest"
    container_name: hostap
    restart: always
    network_mode: host
    privileged: true
    environment:
      - INTERFACE=wlan0
      - CHANNEL=6
      - SSID=hokuyo
      - AP_ADDR=192.168.2.1
      - SUBNET=192.168.2.0
      - WPA_PASSPHRASE=hokuyo123
      - OUTGOINGS=eth0
  fusioneye_web:
    image: "leontius/fusioneye_web:latest"
    container_name: fusioneye
    restart: always
    hostname: fusioneye_web
    ports:
      - "9000:80"
    depends_on:
      - ros
    networks:
      - eye
networks:
   eye:
